-- ============================================================
-- CSC Center — Supabase setup + SAFE-MODE security
-- Run ONCE:  Supabase Dashboard → SQL Editor → New query → paste → Run
-- Safe to re-run (idempotent).
--
-- Security model (who can do what through the public anon key):
--   • anon (any website visitor)
--       - contact_us    : INSERT only  (submit the form; canNOT read others' data)
--       - notifications : SELECT active rows only (read announcements)
--       - services      : SELECT only  (read service list)
--   • authenticated (the logged-in admin)
--       - full read/write on all three tables
--
-- IMPORTANT: this only stays safe if random people can't become
-- "authenticated". After creating your admin user, DISABLE sign-ups:
--   Authentication → Providers → Email → turn OFF "Enable sign ups".
-- ============================================================

-- ---------- Tables ----------
create table if not exists public.contact_us (
  id          bigint generated by default as identity primary key,
  name        text,
  email       text,
  phone       text,
  village     text,
  service     text,
  created_at  timestamptz not null default now()
);

create table if not exists public.notifications (
  id          bigint generated by default as identity primary key,
  title       text not null,
  description text,
  deadline    date,
  active      boolean not null default true,
  created_at  timestamptz not null default now()
);

-- ---------- Enable RLS ----------
alter table public.contact_us    enable row level security;
alter table public.notifications enable row level security;

-- ---------- contact_us policies ----------
-- Remove any older permissive policies first
drop policy if exists "contact_us_anon_all"      on public.contact_us;
drop policy if exists "contact_us_public_insert" on public.contact_us;
drop policy if exists "contact_us_admin_all"     on public.contact_us;

-- Visitors may submit, but cannot read/modify anything
create policy "contact_us_public_insert"
  on public.contact_us for insert to anon with check (true);

-- Logged-in admin can read & manage submissions
create policy "contact_us_admin_all"
  on public.contact_us for all to authenticated using (true) with check (true);

-- ---------- notifications policies ----------
drop policy if exists "notifications_anon_all"     on public.notifications;
drop policy if exists "notifications_public_read"  on public.notifications;
drop policy if exists "notifications_admin_all"    on public.notifications;

-- Visitors can read ONLY active announcements
create policy "notifications_public_read"
  on public.notifications for select to anon using (active is true);

-- Logged-in admin can push / edit / hide / delete
create policy "notifications_admin_all"
  on public.notifications for all to authenticated using (true) with check (true);

-- ---------- services policies (harden the existing open ones) ----------
-- The services table already exists; tighten it the same way.
alter table public.services enable row level security;

-- Drop the previously created open policies (names from the original setup)
drop policy if exists "Enable read access for all users"      on public.services;
drop policy if exists "Enable insert for authenticated users" on public.services;
drop policy if exists "Enable delete for authenticated users" on public.services;
drop policy if exists "Enable update for authenticated users" on public.services;
drop policy if exists "services_public_read" on public.services;
drop policy if exists "services_admin_all"   on public.services;

create policy "services_public_read"
  on public.services for select to anon using (true);

create policy "services_admin_all"
  on public.services for all to authenticated using (true) with check (true);

-- ---------- Optional: seed the first announcement ----------
insert into public.notifications (title, description, deadline)
values (
  'CET C Group की नई Vacancy',
  'CET आवेदन के लिए दस्तावेज़ पूरे करें — फीस भुगतान और फॉर्म सबमिशन हम आसान बना देते हैं। अभी नज़दीकी CSC सेंटर पर संपर्क करें।',
  '2026-06-30'
);
