-- ============================================================
-- CSC Center — Supabase setup
-- Run ONCE:  Supabase Dashboard → SQL Editor → New query → paste → Run
-- Safe to re-run (idempotent).
-- Tables match the app code exactly:
--   • ContactForm.jsx        inserts into  contact_us
--   • AdminDashboard.jsx     reads contact_us, reads/writes notifications
--   • Home.jsx               reads active notifications
-- ============================================================

-- 1) Public "Contact Us" submissions (shown in Admin → Contact Requests)
create table if not exists public.contact_us (
  id          bigint generated by default as identity primary key,
  name        text,
  email       text,
  phone       text,
  village     text,
  service     text,
  created_at  timestamptz not null default now()
);

-- 2) Admin-pushed announcements shown on the main (Home) page
create table if not exists public.notifications (
  id          bigint generated by default as identity primary key,
  title       text not null,
  description text,
  deadline    date,
  active      boolean not null default true,
  created_at  timestamptz not null default now()
);

-- ------------------------------------------------------------
-- Access policies (site uses the public ANON key, like the
-- existing "services" table). NOTE: anyone with the anon key can
-- read/write these tables — fine for this simple public site, but
-- do not store sensitive data here.
-- ------------------------------------------------------------
alter table public.contact_us    enable row level security;
alter table public.notifications enable row level security;

drop policy if exists "contact_us_anon_all"     on public.contact_us;
drop policy if exists "notifications_anon_all"   on public.notifications;

create policy "contact_us_anon_all"
  on public.contact_us    for all to anon using (true) with check (true);

create policy "notifications_anon_all"
  on public.notifications for all to anon using (true) with check (true);

-- Optional: seed the first announcement (CET vacancy)
insert into public.notifications (title, description, deadline)
values (
  'CET C Group की नई Vacancy',
  'CET आवेदन के लिए दस्तावेज़ पूरे करें — फीस भुगतान और फॉर्म सबमिशन हम आसान बना देते हैं। अभी नज़दीकी CSC सेंटर पर संपर्क करें।',
  '2026-06-30'
);
